name: Check examples run
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      # Setup Python with caching
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install Python Kernel
        run: |
          pip install ipykernel
          python -m ipykernel install --user --name python3

      - name: Install dependencies
        run: pip install .[dev]

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Install built package
        run: pip install --force-reinstall dist/*.whl

      - name: Remove source
        run: rm -rf ./src

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Checkout PS
        uses: actions/checkout@v6
        with:
          repository: smogon/pokemon-showdown
          path: pokemon-showdown
          submodules: recursive

      - name: Get last showdown commit hash
        id: showdown-hash
        run: |
          cd pokemon-showdown/
          export hash=`git log -1 --pretty=format:%H`
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Restore server cache
        uses: actions/cache@v5
        with:
          path: pokemon-showdown/node_modules
          key: showdown-python3.11-${{ steps.showdown-hash.outputs.hash }}
          restore-keys: showdown-python3.11-

      - name: Install PS dependencies and start server
        run: bash scripts/ci_setup_showdown.sh

      - name: Run example notebooks
        run: |
            for notebook in $(find examples -name '*.ipynb'); do
              jupyter nbconvert --to notebook --execute "$notebook" --output temp.ipynb
              if [ $? -ne 0 ]; then
              echo "Execution of $notebook failed"
              exit 1
              fi
              rm examples/temp.ipynb
            done
