name: Run tests
on:
  workflow_call:
    inputs:
      showdown-ref:
        type: string
        default: '2ddfa0476f8207e12e204b1c69f7c7683b17633c'
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest -x --cov=src/poke_env unit_tests/

      - name: Convert coverage to XML
        run: uv run coverage xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: coverage.xml

      - name: Build package
        run: uv build

      - name: Install built package
        run: uv pip install -p .venv/bin/python --reinstall dist/*.whl

      - name: Remove source
        run: rm -rf ./src

      - name: Run package-based tests
        run: uv run --no-sync pytest -x unit_tests/

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Checkout PS
        uses: actions/checkout@v7
        with:
          repository: smogon/pokemon-showdown
          ref: ${{ inputs.showdown-ref || '2ddfa0476f8207e12e204b1c69f7c7683b17633c' }}
          path: pokemon-showdown
          submodules: recursive

      - name: Get last showdown commit hash
        id: showdown-hash
        run: |
          cd pokemon-showdown/
          export hash=`git log -1 --pretty=format:%H`
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Restore server cache
        uses: actions/cache@v6
        with:
          path: pokemon-showdown/node_modules
          key: showdown-${{ runner.os }}-node24-${{ steps.showdown-hash.outputs.hash }}
          restore-keys: showdown-${{ runner.os }}-node24-

      - name: Install PS dependencies and start server
        timeout-minutes: 3
        run: bash scripts/ci_setup_showdown.sh

      - name: Run integration tests
        run: uv run --no-sync pytest -x integration_tests/

      - name: Upload Showdown log
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: showdown-python${{ matrix.version }}
          path: pokemon-showdown/server.log
          if-no-files-found: ignore
